global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "tf_serving"
    metrics_path: "/monitoring/prometheus/metrics"
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:8501"]